### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by NiceGuy2017** [Tangerinos/Tanji#10]
When I click on Connect, the habbo page does not load. Actually no page loads, google chrome returns error: ERR_CONNECTION_RESET
The internet does not work in any browser. I already delete cookies and cache.

**Comment by Adversities** [comment]
Well pages can't load cause Tanji sets a proxy to intercept the connection between Habbo and you, if habbo doesn't load meants that you didn't allow the custom certificate, the firewall permission or an antivir is blocking the connection... When it does it's work normally Tanji disables the proxy... then you can load pages without problems, that process is pretty fast so you usually dont realize that the proxy was changed.

Possible problems:
* Certificate
* Firewall
* Antivir

**Comment by NiceGuy2017** [comment]
Thanks for answering.
But I've tried using the firewall and the antivirus turned off.
I have already installed the certifying manually by clicking on the file.
I have tried to change the proxy port from 8081 to 8091, etc.
After I formatted my computer it did not work anymore.
Currently, does tanji only work in Habbo USA?
Anyway, I'll keep trying, thank you.

**Comment by Speaqer** [comment]
Tanji works on every official Habbo Hotel site.

**Comment by Adversities** [comment]
Leave us ur Discord or Telegram to make a TeamViewer meeting, in that way we can see what's happening
