### ISSUE TITLE
Problem while intializate tanji.exe

### ISSUE THREAD

**Issue by Afonsopirex** [Tangerinos/Tanji#4]
Hello, My name is Jhon, yesterday I downloaded the tanji rar(on the own website) however Im constantly facing problems to open the program, actually when I click ahead on tanji.exe winRAR says:''C:.......Rar$EXa0.123/tanji.exe, Whats the troubleshooting, what I gotta do.... Wait for reply.

**Comment by Afonsopirex** [comment]
Cannot execute ..... Rar$EXa0.123....

**Comment by legit** [comment]
Extract the files from the archive, then execute tanji.exe in the folder where you've extracted it.

**Comment by Afonsopirex** [comment]
http://prnt.sc/ccrqvo even when I extracted it, the file does not appear please help

**Comment by Speaqer** [comment]
Disable your antivirus software and try download the latest version again.
