### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Nenji** [Tangerinos/Tanji#5]
hi,
I'm still trying to open Tanji, but I always get this exception:

> System.ArgumentOutOfRangeException: Die Länge darf nicht kleiner als 0 (null) sein.
> Parametername: length
>    bei System.String.Substring(Int32 startIndex, Int32 length)
>    bei Eavesdrop.Utilities.INETOptions.SetAddress(String proxyType, String addess)
>    bei Eavesdrop.Utilities.INETOptions.set_HTTPAddress(String value)
>    bei Eavesdrop.Eavesdropper.SetProxyAddresses(UInt16 port, InterceptOptions options)
>    bei Eavesdrop.Eavesdropper.Terminate()
>    bei Tanji.MainFrm.MainFrm_Load(Object sender, EventArgs e)
>    bei System.Windows.Forms.Form.OnLoad(EventArgs e)
>    bei System.Windows.Forms.Form.OnCreateControl()
>    bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    bei System.Windows.Forms.Control.CreateControl()
>    bei System.Windows.Forms.Control.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    bei System.Windows.Forms.Form.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Form.WndProc(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> Tanji
>     Assembly-Version: 1.4.56.0.
>     Win32-Version: 1.4.56.0.
>     CodeBase: file:///C:/Users/Frenk/Desktop/Tanji/Tanji.exe.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> Sulakore
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///C:/Users/Frenk/Desktop/Tanji/Sulakore.DLL.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> Accessibility
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
> ----------------------------------------
> Tangine
>     Assembly-Version: 1.2.0.0.
>     Win32-Version: 1.2.0.0.
>     CodeBase: file:///C:/Users/Frenk/Desktop/Tanji/Tangine.DLL.
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
> ----------------------------------------
> SMDiagnostics
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
> ----------------------------------------
> Eavesdrop
>     Assembly-Version: 1.2.0.0.
>     Win32-Version: 1.2.0.0.
>     CodeBase: file:///C:/Users/Frenk/Desktop/Tanji/Eavesdrop.DLL.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1586.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------

would be nice if you could tell me how to fix this. 👍 
Regards

**Comment by Speaqer** [comment]
Check your browsers LAN Settings and clear all those proxy textboxes.

**Comment by Speaqer** [comment]
It needs look like this, https://i.gyazo.com/48cfe7dac5c225eb641350d0266d41c4.png

**Comment by Speaqer** [comment]
I guess you solved ur problem.
