### ISSUE TITLE
Eavesdrop requires a self-signed certificate

### ISSUE THREAD

**Issue by Wackoz** [Tangerinos/Tanji#9]
Tanji - Alert:
" Eavesdrop requires a self-signed certificate in the root store to intercept HTTPS traffic.
Would you like to retry the process? "

Can't open tanji properly... plus I kinda have issue also with .NET with KERNELLBASE.DLL

Any suggestion?
(Tanji/Novo used to work well on W8.1... I upgrade to Windows10 and I have all those problems)

**Comment by Speaqer** [comment]
It seem like Eavesdropper has some problems to install the certificate..

1. Download this root certificate from [here](http://www.mediafire.com/file/a8af7hc06wvxo6e/EavesdropRoot.cer) or export it from [here](https://github.com/Tangerinos/Tanji/files/758632/EavesdropRootCertificate.zip)


2. Install the certificate on your browser. You can find some [tutorials](http://lmgtfy.com/?q=how+to+install+root+certificate+on+google+chrome) for Google Chrome which I recommend you to use with Tanji.

**Comment by Wackoz** [comment]
Ok I finally solved it! I can finally open Tanji, thank you so much

Now Tanji seems have problem to connect properly... When I try to connect with tanji, Habbo can't load the page at all
